# Generated by Django 3.2 on 2021-06-22 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgmiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solo_21_6_2021',
            name='bgmiuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
