# Generated by Django 3.2 on 2021-06-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgmiapp', '0002_alter_solo_21_6_2021_bgmiuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solo_21_6_2021',
            name='bgmiuser',
        ),
        migrations.AddField(
            model_name='solo_21_6_2021',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bgmiapp.profile'),
        ),
    ]
