# Generated by Django 3.2 on 2021-06-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgmiapp', '0004_duo_21_6_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='squad_21_6_2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_pubg_id', models.PositiveIntegerField()),
                ('player1_pubg_name', models.CharField(max_length=15)),
                ('player2_pubg_id', models.PositiveIntegerField()),
                ('player2_pubg_name', models.CharField(max_length=15)),
                ('player3_pubg_id', models.PositiveIntegerField()),
                ('player3_pubg_name', models.CharField(max_length=15)),
                ('player4_pubg_id', models.PositiveIntegerField()),
                ('player4_pubg_name', models.CharField(max_length=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bgmiapp.profile')),
            ],
        ),
    ]
