# Generated by Django 3.2 on 2021-06-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgmiapp', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
