# Generated by Django 3.2 on 2021-06-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmiapp', '0007_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
