# Generated by Django 3.2 on 2021-06-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmiapp', '0008_profile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.AddField(
            model_name='solo_21_6_2021',
            name='Prize_amoubt',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='solo_21_6_2021',
            name='position',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
