# Generated by Django 3.2 on 2021-06-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgmiapp', '0009_auto_20210627_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solo_21_6_2021',
            old_name='Prize_amoubt',
            new_name='prize_amount',
        ),
    ]
