# Generated by Django 3.2 on 2021-06-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgmiapp', '0010_rename_prize_amoubt_solo_21_6_2021_prize_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_amount', models.PositiveSmallIntegerField(verbose_name='Enter Amount')),
                ('UPI_ID', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bgmiapp.profile')),
            ],
        ),
    ]
