# Generated by Django 3.2 on 2021-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmiapp', '0012_solo_21_6_2021_form_submited'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='form_submited',
            field=models.BooleanField(default=False),
        ),
    ]
