# Generated by Django 3.2 on 2021-07-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgmiapp', '0013_profile_form_submited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solo_21_6_2021',
            name='form_submited',
        ),
    ]
