# Generated by Django 3.2 on 2021-07-06 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgmiapp', '0014_remove_solo_21_6_2021_form_submited'),
    ]

    operations = [
        migrations.CreateModel(
            name='solo_20_6_2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_pubg_id', models.PositiveIntegerField()),
                ('player1_pubg_name', models.CharField(max_length=15)),
                ('position', models.CharField(default='0', max_length=20)),
                ('prize_amount', models.CharField(default='0', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bgmiapp.profile')),
            ],
        ),
    ]
